apiVersion: v1
kind: Service
metadata:
  namespace: tor
  name: logstash
  labels:
    app: logstash
spec:
  clusterIP: None
  ports:
  - name: logstash-tcp
    port: 5000
  selector:
    app: logstash
---
apiVersion: v1
kind: Service
metadata:
  namespace: tor
  name: logstash-nodeport
  labels:
    app: logstash
spec:
  type: NodePort
  ports:
  - name: logstash-tcp
    port: 5000
    targetPort: 5000
    nodePort: 30921
  selector:
    app: logstash
