apiVersion: v1
kind: ConfigMap
metadata:
  namespace: tor
  name: logstash-configmap
  labels:
    task: logging
    k8s-app: logstash
data:
  logstash.yml: |
    http.host: "127.0.0.0"
    path.config: /usr/share/logstash/pipeline
  logstash.conf: 
    input 
    {
      jdbc {
        jdbc_driver_library => "/tmp/mysql-connector-java-8.0.18.jar"
        jdbc_driver_class => "com.mysql.jdbc.Driver"
        jdbc_connection_string => "jdbc:mysql://mysql-svc:3306/kurly?serverTimezone=Asia/Seoul"
        jdbc_user => "kurly"
        jdbc_password => "kurly"
        jdbc_paging_enabled => true
        statement => "SELECT * FROM product WHERE DATE_SUB(updatedAt, INTERVAL 9 HOUR) > :sql_last_value"
        schedule => "* * * * *"
      }
    }
    filter 
    {
      mutate {
        copy => { "id" => "[@metadata][_id]"}
        remove_field => ["id", "@version", "unix_ts_in_secs"]
      }
    }
    output
    {
      elasticsearch
      {
        hosts => ["elasticsearch:9200"]
        index => "product"
      }      
    }
