apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: tor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
     metadata:
       labels:
         app: mysql
     spec:
       #nodeName: worker1
       containers:
       - image: mysql:5.6
         name: mysql-pod
         env:
         - name: MYSQL_ROOT_PASSWORD
           valueFrom:
              secretKeyRef:
                name: mysql-secret
                key: password
         ports:
         - containerPort: 3306
         volumeMounts:
         - name: mysql-persistent-storage
           mountPath: /var/lib/mysql
         - name: tz-seoul
           mountPath: /etc/localtime  
         resources:
           limits:
             cpu: "2000m"
             memory: "4096Mi"
           requests:
             cpu: "2000m"
             memory: "4096Mi"
       volumes:
       - name: mysql-persistent-storage
         persistentVolumeClaim:
            claimName: mysql-pvc
       - name: tz-seoul
         hostPath:
           path: /usr/share/zoneinfo/Asia/Seoul     

