apiVersion: v1
kind: ServiceAccount
metadata:
  name: github-action
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: tor
  name: github-action-role
rules:
- apiGroups: ["","apps"]
  resources: ["pods","services","configmap","secrets","deployments"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: github-action-rolebinding
  namespace: tor
subjects:
- kind: ServiceAccount
  name: github-action
roleRef:
  kind: Role
  name: github-action-role
  apiGroup: rbac.authorization.k8s.io
